# This is a basic workflow to help you get started with Actions

name: Testing Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildv1:
    # Name of job
    name: checking the shell script
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # If repository secret found then its value will appear as => ***

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ secrets.API_KEY_02 }}
          echo ${{ secrets.API_KEY_01 }}
          touch script.py
          echo hello > readme_v1.md
          python script_v1.py
          ls -la
          python ${{secrets.Py_File_Name_01}}
          tree
      - name: Check condition
        run: echo hello i am testing if condition so dont take it personally!
        if: github.event_name == 'push'
      - name: Check the github event name
        run: |
          echo github event name is ${{github.event_name}}
